DATOS SEGMENT ; DEFINICION DE SEGMENTO DE DATOS
    IMPRESION DB "HOLA MUNDO","$" ;$ PARA TERMINAR LA CADENA
DATOS ENDS ; FIN DE SEGMENTO DE DATOS


PILA SEGMENT STACK "STACK" ; DEFINICION DE SEGMENTO DE PILA
    DB 32 DUP("STACK___")
PILA ENDS  ; FIN DE SEGMENTO DE PILA


CODE SEGMENT "CODE" ; DEFINICION DE SEGMENTO DE CODIGO
    ASSUME CS:CODE,DS:DATOS,SS:PILA
    MAIN PROC FAR ; INICIO DEL PROCEDIMIENTO PRINCIPAL START
        MOV AX,DATOS           ;MUEVE EL SEGMENTO DE DATOS A AX
        MOV DS,AX              ;MUEVE AX A DS
        MOV AH,09H             ;PETICI?N PARA DESPLEGAR DATOS EN PANTALLA
        MOV DX,OFFSET IMPRESION  ;MOVER A DX EL DESPLAZAMIENTO O POSICI?N DE LA VARIABLE LETRERO
        INT 21H                ;PETICI?N DE FUNCI?N AL DOS
        RET                    ;RETORNO DE SUBRUTINA
    MAIN ENDP     ; FIN DEL PROCEDIMIENTO PRINCIPAL START
CODE ENDS ; FIN DEL SEGMENTO DE CODIGO 

END MAIN ; FIN DEL PROGRAMA